name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt' # Use AdoptOpenJDK

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Install Microsoft Edge and EdgeDriver
        run: |
          sudo apt update
          sudo apt install -y wget software-properties-common
          wget https://packages.microsoft.com/keys/microsoft.asc -q -O - | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt install -y microsoft-edge-stable
          sudo apt install -yqq unzip
          
          # Detect the version of Microsoft Edge
          EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+' || echo "128.0.0")
          echo "Detected Edge version: $EDGE_VERSION"
          
          # Fetch the corresponding EdgeDriver version
          EDGEDRIVER_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_RELEASE_$EDGE_VERSION || echo "128.0.0")
          
          if [ -z "$EDGEDRIVER_VERSION" ]; then
            EDGEDRIVER_VERSION="128.0.0" # Default to a stable version if detection fails
          fi
          
          echo "Using EdgeDriver version: $EDGEDRIVER_VERSION"
          wget -O /tmp/edgedriver.zip https://msedgedriver.azureedge.net/$EDGEDRIVER_VERSION/edgedriver_linux64.zip
          
          sudo unzip /tmp/edgedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/msedgedriver
          msedgedriver --version

      - name: Verify Java installation
        run: java -version

      - name: Run Maven tests with debug
        run: mvn clean test -X
