name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: 'adopt' # You can use Amazon Corretto, AdoptOpenJDK, etc.

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: latest

      - name: Set up ChromeDriver
        uses: actions/setup-chromedriver@v2
        with:
          version: latest

      - name: Run Maven tests
        run: mvn test -X
