name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # Updated to Eclipse Temurin for Java 11

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Verify Java installation
        run: java -version

      - name: Install dependencies
        run: mvn install

      - name: Run Maven tests
        run: mvn clean test -X # Keeping -X for debugging
        continue-on-error: false # Change this to true if you want the job to proceed on errors

      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: extent-spark-report
          path: C:\Users\Carlos Ozoria\eclipse-workspace\CitizensFLAProject\ExtentSparkReport.html

      - name: Always upload test report on failure
        if: failure() || success()
        uses: actions/upload-artifact@v3
        with:
          name: extent-spark-report
          path: C:\Users\Carlos Ozoria\eclipse-workspace\CitizensFLAProject\ExtentSparkReport.html
