name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 for the project
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Verify Java installation
      - name: Verify Java installation
        run: java -version

      # Step 5: Install Maven dependencies
      - name: Install dependencies
        run: mvn install -DskipTests

      # Step 6: Run Maven tests
      - name: Run Maven tests
        run: mvn test

# Add this to your GitHub Actions YAML file
      # Step 7: Archive the Extent Report
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: extent-spark-report
          path: ./CICD.testReport/ExtentSparkReport_*.html  # Use wildcard to capture all reports

      # Step 8: Always upload test report on failure
      - name: Always upload test report on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-failure-reports
          path: ./test-output  # Adjust based on your project structure

